SET SERVEROUTPUT ON;

CREATE TABLE LOG_NEWEMP (ENTRY_ID NUMBER(20), USERNAME VARCHAR2(30), CURDATE TIMESTAMP, FIRST_NAME VARCHAR2(200), LAST_NAME VARCHAR2(200));
CREATE SEQUENCE LOG_NEWEMP_SEQ;
EXECUTE emp_pkg.add_employee('Max', 'Smart', 20);
EXECUTE emp_pkg.add_employee('Clark', 'Kent', 10);
ROLLBACK;
SELECT * FROM log_newemp;